### ISSUE TITLE
Feature: Support for Identifying Unused CRDs

### ISSUE THREAD

**Issue by m-yosefpor** [yonahd/kor#103]
**Is your feature request related to a problem? Please describe.**
While Kor is an excellent tool for identifying unused Kubernetes resources, it currently does not support identifying unused Custom Resource Definitions (CRDs). In large Kubernetes clusters, it's not uncommon to have CRDs that were once used but no longer have any instances created from them. Identifying these unused CRDs can help in cleaning up and maintaining a lean cluster configuration.

**Describe the solution you'd like**
I'd like Kor to have the capability to identify and list unused CRDs, i.e., CRDs for which no instances have been created. This can be an additional subcommand, similar to the existing ones like `configmap`, `secret`, etc. For example: `kor crd` could list all the unused CRDs in the specified namespace or all namespaces.

**Describe alternatives you've considered**
One could manually check for CRD instances using `kubectl`, but this is cumbersome and not scalable for large clusters. Having this feature integrated into Kor would streamline the process and make it consistent with the identification of other unused resources.

**Additional context**
As Kubernetes continues to evolve and organizations adopt more custom resources, the ability to identify unused CRDs will become increasingly important for cluster hygiene. Adding this feature would further enhance Kor's value proposition as a comprehensive Kubernetes resource management tool.

**Comment by yonahd** [comment]
Thanks for the proposal! 

The approach to this would be to list the available CRDs in the cluster and then for each see if there are usages of that CRD

**Comment by yonahd** [comment]
If someone can take this it would be awesome!

**Comment by hzliangbin** [comment]
@yonahd May I have a try？

**Comment by m-yosefpor** [comment]
Oh sorry I forgot to mention here, I implemented the feature already.. So shall I open a PR for this now?

@hzliangbin @yonahd

**Comment by yonahd** [comment]
> Oh sorry I forgot to mention here, I implemented the feature already.. So shall I open a PR for this now?
> 
> @hzliangbin @yonahd

If you already implemented it, open the pr.

**Comment by hzliangbin** [comment]
@yonahd take it
