### ISSUE TITLE
Feature: Add more customization and filtering options for finding unused resources

### ISSUE THREAD

**Issue by Azhovan** [yonahd/kor#105]
**Is your feature request related to a problem? Please describe.**
I would like to have more control over the criteria and scope of the search for unused resources. For example, I may want to exclude some resources that have certain labels or annotations, or only list resources that are older or larger than a certain threshold.

**Describe the solution you'd like**
I would like to have more flags or options to customize and filter the search query. For example, I could use something like `--exclude-label owner:alice` or `--min-age 24h` or `--min-size 1Mi` to refine the results.

**Describe alternatives you've considered**
An alternative solution could be to use another tool or script to filter the output of yonahd/kor, but that would be less convenient and efficient.

**Additional context**

**Comment by yonahd** [comment]
Love the idea!
This can definitely be helpful to our users. The challenge here is supporting the filters that are not part of kubectl such as age. 

This is open for contribution

**Comment by Azhovan** [comment]
@yonahd 
I would be happy to contribute to this part too, please feel free to assign it to me!

**Comment by yonahd** [comment]
Assigned.
Would love to hear your plan for this feature as at first glance it seems like it has many sub-features and I would like for this solution to be extendable

**Comment by Azhovan** [comment]
These are three area that I think should be touched: 
- **First**, I would define a new struct called `FilterOptions` that would store the various flags and options for customizing and filtering the search query. For example, it would have fields like `ExcludeLabel`, `MinAge`, `MinSize`, etc. This would make it easier to pass the parameters to the functions that list the resources and to validate the user input. we can easily add more fields to the struct if we need more options in the future. We can also use methods or functions to validate or manipulate the values of the fields.

- **Second**, I would modify the existing functions that list the resources in the cluster, such as `GetUnusedXXXStructured` and `GetUnusedXXX` (although I think this area also should be refactored some times in the future to reduce the amount of duplicated code that already exist, but that is different story!) I would use the Kubernetes API selectors to filter by labels or annotations, or compare the creation time or size of the resources with the given thresholds. This would make the functions more flexible and adaptable to different scenarios.

- **Third**, I would update the CLI interface to parse the flags and options from the user input and create a FilterOptions object accordingly

**Comment by yonahd** [comment]
Sounds like a solid plan. Go for it!

It's important to allow these to be optional and allow for future filters to be easily added to it.

Regarding the duplicate code, we are aware and are thinking of a way to refactor this and a couple of other duplicates.
