### ISSUE TITLE
Feature: Add a flag or option to schedule the scan and deletion at a regular interval

### ISSUE THREAD

**Issue by Azhovan** [yonahd/kor#122]
**Is your feature request related to a problem? Please describe.**
I am using Kor to scan (and delete in the future) unused resources in my cluster, but I have to run it manually every time I want to clean up my cluster. This is tedious and time-consuming, and sometimes I forget to do it.
I would like to have a way to automate this process and run it periodically without my intervention.

**Describe the solution you'd like**
I would like to have a flag or option in Kor that allows me to schedule the scan and deletion of unused resources at a regular interval, such as daily, weekly, or monthly. This would automate the process of cleaning up my cluster and keep it optimized and efficient. For example, I could run kor -interval daily to run the scan and deletion every day at a fixed time.

**Describe alternatives you've considered**
I have considered using cron jobs in Linux or Github actions to run Kor at a regular interval, but they are not very convenient or flexible for me. I have to create and maintain a separate script or command for each cluster or namespace that I want to scan and delete, and I have to deal with different syntaxes and configurations for each platform.

**Additional context**

**Comment by yonahd** [comment]
Thanks for the request.
Did you consider using the Helm chart https://github.com/yonahd/kor#in-cluster-usage ?
This offers continuous scanning with either Slack reports or Prometheus metrics

**Comment by Azhovan** [comment]
> Thanks for the request. Did you consider using the Helm chart https://github.com/yonahd/kor#in-cluster-usage ? This offers continuous scanning with either Slack reports or Prometheus metrics

Thanks. I think the feature request that I suggested is still worth it, even considering the Helm feature you linked.
Here are some reasons why:

- The Helm chart for Kor requires users to have Helm installed and configured on their cluster, which may not be the case for everyone.
- The Helm chart for Kor does not offer automatic deletion of unused resources which can be added in the future probably. The flag or option that I proposed would allow users to choose whether they want to delete the unused resources or not(with another flag like --dry-run combined).
- The flag or option that I suggested would use a simple and flexible syntax, such as daily, weekly, or monthly, to set the interval in compare to cronjob regex! 

what do you think?

**Comment by yonahd** [comment]
@Azhovan Not sure I follow.
Helm is not installed in a cluster, it is a CLI for packaging and installing Kubernetes applications.

The Helm chart allows running Kor as a cronjob(you can choose the interval).
The delete flag(which is being worked on now) will come with a force flag that should be able to run as part of the chart.

Do you see a usage for a scheduler in the CLI itself?

**Comment by Azhovan** [comment]
Sorry for confusion I had a typo! what I meant is some users may not want to use Helm or may not have it installed on their `machine`. They may prefer to use Kor as a **standalone** tool without any dependencies or additional steps.

I think having scheduler internally in the CLI provide great user experience, lets me give you an **example**:  Lets say users may want to have different intervals and times for different clusters or namespaces. They may want to run Kor more frequently or less frequently depending on the size or activity of their cluster or namespace. Having a scheduler in the CLI would allow them to use different commands for different clusters or namespaces, such as: 
-  `kor --cluster prod --interval daily` 
-  `kor -namespace dev --interval weekly` 

Now lets say they may want to get an overview of the all defined schedules like: 
- `kor  --list-schedulers`  

Or they may change a specific schedule like: 
- `kor -edit-scheduler <name>`

**Comment by Azhovan** [comment]
@yonahd 
what do you think? did my description make it clear?

**Comment by yonahd** [comment]
Hey @Azhovan 
I understand the use case, still think it can be done with an external option suck is local cron.
Because of that, I don't want to embed it into the CLI.

Thanks for the suggestion!

**Comment by Azhovan** [comment]
@yonahd could you please elaborate more on why you don’t want to embed the scheduler in the CLI?

**Comment by yonahd** [comment]
> @yonahd could you please elaborate more on why you don’t want to embed the scheduler in the CLI?

Mainly for the reasons I stated above. But here is a more elaborate explanation:

- Adding a scheduler increases the complexity of the tool. If the scheduling aspect isn't crucial or if it's simpler to have users rely on external schedulers (like Cron jobs for Unix-based systems), it might be unnecessary to embed a scheduler directly into the tool.
- Consider the user experience. If the CLI tool is aimed at technical users familiar with scheduling concepts, integrating a scheduler might add value. However, if the tool is for more general users, it might be better to keep the CLI focused on core functionality and allow users to use separate scheduling tools.
- Integrating a scheduler adds dependencies and maintenance overhead. You'll need to consider updates, potential issues with the scheduler library, and how it affects the overall maintenance of your tool.

**Comment by Azhovan** [comment]
Thanks for your response, However, I still think having a scheduler in the CLI would be a valuable addition to  Kor. 

- **Complexity**: I agree that adding a scheduler increases the complexity of the tool, but I don’t think it is unnecessary or redundant. There are many scenarios where users may want to have different schedules for different clusters or namespaces, or change the schedules dynamically according to their needs. Having a scheduler in the CLI would allow them to do that easily and flexibly, without relying on external schedulers that may have different syntaxes or configurations. 
- **User experience**: I disagree that the CLI tool is aimed at general users who are not familiar with scheduling concepts. I think most of the users of your tool are technical users who are working with Kubernetes and have some knowledge of scheduling and automation. They would appreciate having a scheduler in the CLI that allows them to specify the frequency and time of the cleanup operations, and get an overview of the defined schedules.
- **Maintenance**: I understand that integrating a scheduler adds dependencies and maintenance overhead, but I don’t think it is a major issue or obstacle. There are many open-source and well-tested scheduler libraries that you can use, such as [gocron](https://github.com/go-co-op/gocron), [go-quartz](https://github.com/reugn/go-quartz), or [gronx](https://github.com/adhocore/gronx). I think this would reduce the burden and risk of implementing and maintaining the scheduler in the CLI, not increase it.

**Comment by Azhovan** [comment]
@yonahd what do you think?

**Comment by yonahd** [comment]
> @yonahd what do you think?

I understand. At least at this point I think there are other things that are more core functionality that should be focused on.
