### ISSUE TITLE
Feature: Print version on startup

### ISSUE THREAD

**Issue by yonahd** [yonahd/kor#130]
**Is your feature request related to a problem? Please describe.**
When running in cluster we should be able to clearly see the version of kor on startup

**Describe the solution you'd like**
Print the version on startup
e.g. `v0.2.7`

**Comment by sidkhuntia** [comment]
Can i work on it ? and can you point me in some direction? Thank you

**Comment by yonahd** [comment]
> Can i work on it ? and can you point me in some direction? Thank you

Sure.

Take a look at https://github.com/yonahd/kor/blob/main/pkg/utils/banner.go
And https://github.com/yonahd/kor/blob/main/cmd/kor/root.go#L48

**Comment by sidkhuntia** [comment]
Hey, i just wanted to ask where can i get the current version number of kor running
@yonahd

**Comment by yonahd** [comment]
This comes from the git tag.
It would need to be embedded during build time possibly in the goreleaser

**Comment by sidkhuntia** [comment]
Sorry, it is taking me some time, as i have some tests coming up in my class. I will try my best to fix the issue, i need some time

**Comment by yonahd** [comment]
No rush

**Comment by sidkhuntia** [comment]
@yonahd 
I plan to update the `.goreleaser.yml` to add 
```yaml
builds:
  - id: OS
    ldflags:
      - -X github.com/yonahd/kor/pkg/utils.version={{.Version}}
snapshot:
  name_template: "{{ .Version }}"
```

that way I guess I can access the version from the git tag
Does this look good?


I wanted to ask where should I print the version and the format of it ?

**Comment by yonahd** [comment]
> @yonahd I plan to update the `.goreleaser.yml` to add
> 
> ```yaml
> builds:
>   - id: OS
>     ldflags:
>       - -X github.com/yonahd/kor/pkg/utils.version={{.Version}}
> snapshot:
>   name_template: "{{ .Version }}"
> ```
> 
> that way I guess I can access the version from the git tag Does this look good?
> 
> I wanted to ask where should I print the version and the format of it ?

I would need to test this.
I want to add it in the utils just like the printing of the kor banner

**Comment by sidkhuntia** [comment]
![image](https://github.com/yonahd/kor/assets/77291662/c4a6e250-3f33-4fbd-bff1-9188f4265058)

is this formatting okay ?

**Comment by yonahd** [comment]
Perfect
