### ISSUE TITLE
Support Hpa resource 

### ISSUE THREAD

**Issue by yonahd** [yonahd/kor#14]
Kor should be able to find hpa's that are not pointing at any service. Add the command and logic.

**Comment by shay-legit** [comment]
happy to contribute - will do this :)

quick thought:
1. grab hpa.Spec.ScaleTargetRef.Kind + hpa.Spec.ScaleTargetRef.Name from the hpa object spec (both are required, so if there's an hpa - they exist)
2. check if the kind-name pair exists in the cluster - if they don't - return diff

- i don't think we should check for # of replicas in this case as it might give unwanted results, e.g it's good for the unused deployments finding maybe, but not for the hpa, in my opinion - if there's an hpa, and there's a matching deployment or a statefulset for it - it's not unused.

thoughts?

**Comment by yonahd** [comment]
Hi @shay-legit Thanks for the initiative!
That's my thought process exactly `hpa.Spec.ScaleTargetRef.Kind` and `hpa.Spec.ScaleTargetRef.Name` should be the indicators here whether the HPA is unused.

**Comment by shay-legit** [comment]
hi @yonahd - sorry for the delay, mostly have some free time on the weekends :)
i created a draft [pr](https://github.com/yonahd/kor/pull/22/files) in my fork, tried to follow your patterns more or less, lmk if this the direction? happy to do changes.

tested on all namespaces, specific namespace, json output, tabular output.

![image](https://github.com/yonahd/kor/assets/80197570/b75a9a83-3a90-47d1-93ea-642cb686a84a)
![image](https://github.com/yonahd/kor/assets/80197570/0e12c2f0-5281-4f8c-8ae6-3191bbaa4220)

**Comment by yonahd** [comment]
Thanks!
We'll review
