### ISSUE TITLE
cronjob was not working properly

### ISSUE THREAD

**Issue by srujansunny** [yonahd/kor#157]
I set up a cron job for 1 * * * *, but it continues to execute every hour instead of the expected one-minute interval.  What's causing the issue with the cron job's proper functionality

**Comment by yonahd** [comment]
This is not a Kor related question.

Regardless
If you want it to run every minute run `* * * * *`
I don't recommend running it so many frequently but enjoy..

**Comment by srujansunny** [comment]
@yonahd if was running this  * * * * * I'm getting issue that is stating the error in cronjob.yaml file at line no.8

**Comment by yonahd** [comment]
This is again unrelated to kor specifically.
This might be because you removed quotes or something like that.

Please limit the use of these tickets to kor specific issues
