### ISSUE TITLE
Feature: Add contributing.md to the repo

### ISSUE THREAD

**Issue by yonahd** [yonahd/kor#164]
Add a CONTRIBUTING.md file to Kor repository

**Comment by mzsrtgzr2** [comment]
give me that thanks

**Comment by doronkg** [comment]
As adding new orphaned resources capabilities requires the addition/modification of multiple files in the repo, it'd be quite beneficial for new contributors if all were listed properly under `CONTRIBUTING.md` with some level of elaboration.

If I'm not mistaken, this would be the list:
```
.
├── cmd/kor
│   └── <resource>s.go
├── pkg/kor
│   ├── all.go
│   ├── create_test_resources.go
│   ├── delete.go
│   ├── multi.go
│   ├── <resource>s.go
│   └── <resource>s_test.go
└── README.md
```

**Comment by yonahd** [comment]
> As adding new orphaned resources capabilities requires the addition/modification of multiple files in the repo, it'd be quite beneficial for new contributors if all were listed properly under `CONTRIBUTING.md` with some level of elaboration.
> 
> If I'm not mistaken, this would be the list:
> 
> ```
> .
> ├── cmd/kor
> │   └── <resource>s.go
> ├── pkg/kor
> │   ├── all.go
> │   ├── create_test_resources.go
> │   ├── delete.go
> │   ├── multi.go
> │   ├── <resource>s.go
> │   └── <resource>s_test.go
> └── README.md
> ```

100% agree.

**Comment by yonahd** [comment]
@mzsrtgzr2 do you intend to work on this or should I open it up to a different contributor?

**Comment by doronkg** [comment]
> As adding new orphaned resources capabilities requires the addition/modification of multiple files in the repo, it'd be quite beneficial for new contributors if all were listed properly under `CONTRIBUTING.md` with some level of elaboration.
> 
> If I'm not mistaken, this would be the list:
> 
> ```
> .
> ├── cmd/kor
> │   └── <resource>s.go
> ├── pkg/kor
> │   ├── all.go
> │   ├── create_test_resources.go
> │   ├── delete.go
> │   ├── multi.go
> │   ├── <resource>s.go
> │   └── <resource>s_test.go
> └── README.md
> ```

Also in:
```
 .
 └── charts/kor/templates
     └── role.yaml
 ```
