### ISSUE TITLE
kor all -n displays non namespaced resources

### ISSUE THREAD

**Issue by cmk-jarek** [yonahd/kor#178]
**Describe the bug**
kor all -n displays non namespaced resources

**To Reproduce**
"have non namspaced orphaned recources like CRD's in your cluster" 
kor all -n default

**Expected behavior**
when i specify explicit Namespaces, i want to ONLY have the resources in those namespaces evaluated.

**Screenshots**
wouldnt help as the issue seems clear

**OS version, architecture and kor version**
Linux x86_64
Kor version: 0.3.2

**Comment by yonahd** [comment]
We'll take this as a bug. 
I think we'll change the default behavior to be only namespaced resources and put the non namespaced resources behind a flag

**Comment by cmk-jarek** [comment]
Thank you. Already glimpsed into the code and wanted to send a pr, but as the year nears its end im kinda busy. lets see who comes first!  :)

**Comment by arielsashcov** [comment]
Hey I can take this

**Comment by doronkg** [comment]
@arielsashcov note that `GetUnusedAll()` now calls both `GetUnusedAllNamespaced()` & `GetUnusedAllNonNamespaced()` so the new separation might aid you resolving this issue (see #216, #227).

**Comment by doronkg** [comment]
/assign
WIP in #258
