### ISSUE TITLE
Feature: Add a version subcommand

### ISSUE THREAD

**Issue by sgaunet** [yonahd/kor#211]
**Is your feature request related to a problem? Please describe.**
I would like to be able to get the version of the tool by running the version subcommand. 

**Describe the solution you'd like**
For example:

```
$ kor version
0.3.5
```

**Additional context**
Maybe I can do it if you like.

**Comment by doronkg** [comment]
/assign
WIP in #210, currently refactoring the `--version` flag to `version` subcommand.
