### ISSUE TITLE
Failed to run on OpenShift 4.x

### ISSUE THREAD

**Issue by hrytsai** [yonahd/kor#213]
**Describe the bug**
When run kor with parameters 
kor all -n kor-test-namespace we got an error 

> Failed to retrieve namespaces: namespaces is forbidden: User "kor-test-user" cannot list resource "namespaces" in API group "" at the cluster scope

**To Reproduce**
Run kor with option "-n <namespace_name>" 

**Expected behavior**
Namespace will be scanned and result provided

**Screenshots**

**OS version, architecture and kor version**
e.g. Windows 10 x86_64
Kor version: v0.3.5

**Additional context**
OpenShift doesn't allow user to get list of namespaces. 
For example: 
kubectl get ns will return 

> Error from server (Forbidden): namespaces is forbidden: User "kor-test-user" cannot list resource "namespaces" in API group "" at the cluster scope

but when you run: 
kubectl get project 
you will get result: 

NAME DISPLAY NAME STATUS
...
kor-test-namespace
...

**Comment by yonahd** [comment]
Thanks for opening this issue. It seems to be a regression which we'll address.
In the meantime can you try with version 0.3.3

**Comment by hrytsai** [comment]
Great job 
Thank you for fast response, will be waiting for new release to test it

**Comment by yonahd** [comment]
@hrytsai a new release was published. Can you please give it a try?

If you have any issues or further feedback please feel free to open another issue here or in our discord
