### ISSUE TITLE
Scan Traefik IngressRoute resources for references to secrets

### ISSUE THREAD

**Issue by lol768** [yonahd/kor#232]
Consider looking at `kind: IngressRoute` CRDs which specify, within their `spec`:

```
tls:
  secretName: NameOfSecret
```

In order to consider a secret used (or at the very least, document the fact that there are potential false positives when Traefik's non-standard IngressRoutes are in use)

**Comment by yonahd** [comment]
Hi @lol768
Thanks for the feedback!

This is a known issue and we'll make it clearer in this chart https://github.com/yonahd/kor?tab=readme-ov-file#supported-resources-and-limitations that we don't support resources reffered in CRDs(there are simply too many) .

Let us know if you come across anything else
