### ISSUE TITLE
Map false unused resources: Kind

### ISSUE THREAD

**Issue by yonahd** [yonahd/kor#235]
Find all default resources in a kind cluster that kor flags as unused.
List them
Create an issue to exclude them
Bonus: Open merge request with the exclusions
(example can be found here)

**Comment by yonahd** [comment]
I have docker.io-hostpath in kind (macos)

**Comment by doronkg** [comment]
As mentioned in https://github.com/yonahd/kor/pull/241#issuecomment-2077220002, multiple resources are similar between `minikube` & `kind`. 

@yonahd should I append the differences to the existing exclusion lists for each resource, or await #253?

**Comment by doronkg** [comment]
> I have docker.io-hostpath in kind (macos)

I can perform checks both for Windows & Linux installations, but don't have MacOS, so I'll add that.
Have we performed `minikube` checks for all these distributions as well? @cecobask

**Comment by cecobask** [comment]
Hi @doronkg,

I tested the minikube changes on a MacOS only. Might have to investigate further in a separate ticket. Feel free to open up an issue and I can pick it up soon.

**Comment by doronkg** [comment]
> Hi @doronkg,
> 
> 
> 
> I tested the minikube changes on a MacOS only. Might have to investigate further in a separate ticket. Feel free to open up an issue and I can pick it up soon.

I can take a look on the other OSs for `minikube` and see if additional resources are required for exclusion.

I'd appreciate if you can assist me with checking `kind` on MacOS after I'll submit the PR to see if more resources should be excluded.

**Comment by yonahd** [comment]
> > Hi @doronkg,
> > I tested the minikube changes on a MacOS only. Might have to investigate further in a separate ticket. Feel free to open up an issue and I can pick it up soon.
> 
> I can take a look on the other OSs for `minikube` and see if additional resources should be excluded.
> 
> I'd appreciate if you can assist me with checking `kind` on MacOS after I'll submit the basic PR to see if more resources should be excluded.

I'll make sure you get it all from macos

**Comment by doronkg** [comment]
> As mentioned in https://github.com/yonahd/kor/pull/241#issuecomment-2077220002, multiple resources are similar between `minikube` & `kind`. 
> 
> 
> 
> @yonahd should I append the differences to the existing exclusion lists for each resource, or await #253?

@yonahd

**Comment by yonahd** [comment]
> > As mentioned in [#241 (comment)](https://github.com/yonahd/kor/pull/241#issuecomment-2077220002), multiple resources are similar between `minikube` & `kind`.
> > @yonahd should I append the differences to the existing exclusion lists for each resource, or await #253?
> 
> @yonahd

Go ahead with appending. The refactor should be very simple

**Comment by doronkg** [comment]
I've tested `kind` both on Windows & Linux, and all the default unused resources are covered (from source, not via v0.3.8). 
The only difference is mentioned [here](https://github.com/yonahd/kor/pull/241#issuecomment-2077220002) but it was added in #252.
If additional resources are mapped on MacOS, I'll submit a PR to exclude them, if not, this issue could be closed.

**Comment by yonahd** [comment]
service: docker.io-hostpath in kube-system
Thats the only missing one in macos

**Comment by doronkg** [comment]
> > Hi @doronkg,
> > I tested the minikube changes on a MacOS only. Might have to investigate further in a separate ticket. Feel free to open up an issue and I can pick it up soon.
> 
> I can take a look on the other OSs for `minikube` and see if additional resources should be excluded.

I've checked, no additional exceptions where found for `minikube` on Windows/Linux.
