### ISSUE TITLE
Map false unused resources: EKS

### ISSUE THREAD

**Issue by yonahd** [yonahd/kor#236]
Find all default resources in a EKS cluster that kor flags as unused.
List them
Create an issue to exclude them
Bonus: Open merge request with the exclusions
(example can be found here  https://github.com/yonahd/kor/blob/main/pkg/kor/serviceaccounts.go#L16)

**Comment by pbr0ck3r** [comment]
Happy to work on this and get the initial scan.

**Comment by yonahd** [comment]
> Happy to work on this and get the initial scan.

Assigned. Thank you!

**Comment by yonahd** [comment]
@pbr0ck3r are you available for contributing this or should I look to reassign it?

**Comment by pbr0ck3r** [comment]
> @pbr0ck3r are you available for contributing this or should I look to reassign it?

I should be able to do it in the next week.
