### ISSUE TITLE
Map false unused resources: GKE

### ISSUE THREAD

**Issue by yonahd** [yonahd/kor#237]
Find all default resources in a GKE cluster that kor flags as unused.
List them
Create an issue to exclude them
Bonus: Open merge request with the exclusions
(example can be found here  https://github.com/yonahd/kor/blob/main/pkg/kor/serviceaccounts.go#L16)

**Comment by pbr0ck3r** [comment]
Happy to help on this!

**Comment by yonahd** [comment]
> Happy to help on this!

Amazing! Assigned
If you need help with how to do the mapping lmk

**Comment by yonahd** [comment]
Closed with https://github.com/yonahd/kor/pull/252
