### ISSUE TITLE
Refactor: move resource exceptions to external files 

### ISSUE THREAD

**Issue by yonahd** [yonahd/kor#253]
Move the resource exceptions to a different file. 

Currently the lists of exception resource are quite long e.g. https://github.com/yonahd/kor/blob/main/pkg/kor/configmaps.go#L17 and will cause future contributors more cognitive load.

We should separate these from the actual code

**Comment by pbr0ck3r** [comment]
It might be nice to also break out resources into their individual clouds (then merge them all together), so we can better track changes related to specific environments.

- pkg
  - exceptions
    - gke
    - aks
    - kind
    - minikube
    - universal (i.e. kube-proxy)

**Comment by yonahd** [comment]
> It might be nice to also break out resources into their individual clouds (then merge them all together) using a helper function. We can better track changes related to specific environments this way and also allow targeting specific environments.
> 
> * pkg
>   
>   * exceptions
>     
>     * gke
>     * aks
>     * kind
>     * minikube
>     * universal (i.e. kube-proxy)

I was thinking of splitting it using the resource type but this might make more sense. Let's see if there are any takers and we'll see how simply it can be done

**Comment by pbr0ck3r** [comment]
Happy to take a initial stab at this.

**Comment by yonahd** [comment]
Go for it.
Let's see how it looks
