### ISSUE TITLE
Add flag for namespace exception

### ISSUE THREAD

**Issue by yonahd** [yonahd/kor#29]
Add a flag `--exclude` which will make kor run on all namespaces except the one included

**Comment by linrl3** [comment]
@yonahd Could I create a PR for this?

**Comment by yonahd** [comment]
@linrl3 be my guest

**Comment by doryer** [comment]
@yonahd Btw, it will be great if it will accept a list + option to exclude resource when running `all` flag
like kor all --exclude-resource PVC --exclude-namespace foo,bar

**Comment by yonahd** [comment]
@doryer I think this is similar to this issue https://github.com/yonahd/kor/issues/2
We'll get to that soon hopefully
