### ISSUE TITLE
Feature: Add ArtifactHub repository

### ISSUE THREAD

**Issue by Yuni-sa** [yonahd/kor#319]
**Is your feature request related to a problem? Please describe.**
As a continuation to #285 we would want to show kor helm charts on ArtifactHub.

**Describe the solution you'd like**
An ArtifactHub repo should be created and a `artifacthub-repo.yml` should be added to the `gh-pages` branch on the root directory.

**Describe alternatives you've considered**
Host the helm charts on ghcr but we would be missing on the discoverability.

**Additional context**
annotations for artifacthub were added in #306 
example repo: 
https://github.com/kubernetes-sigs/metrics-server/tree/gh-pages

**Comment by Yuni-sa** [comment]
@yonahd it needs the repository-id after you created one.

**Comment by yonahd** [comment]
> @yonahd it needs the repository-id after you created one.

I think I need to create a release with a chart first. It's a requirement for the url in artifactory hub

**Comment by doronkg** [comment]
> > @yonahd it needs the repository-id after you created one.
> 
> 
> 
> I think I need to create a release with a chart first. It's a requirement for the url in artifactory hub 

Today we released `v0.5.3` along with `kor-0.1.10` so I believe we can proceed with that.

**Comment by yonahd** [comment]
> > > @yonahd it needs the repository-id after you created one.
> > 
> > 
> > I think I need to create a release with a chart first. It's a requirement for the url in artifactory hub
> 
> Today we released `v0.5.3` along with `kor-0.1.10` so I believe we can proceed with that.

The chart release workflow failed. I need to investigate

**Comment by Yuni-sa** [comment]
@yonahd I see you fixed the permissions issue and index.yaml was generated. Please create a repository and share the repo ID so we can add the artifacthub-repo.yml file.

**Comment by yonahd** [comment]
Repo ID: ae2f7b72-952c-4a32-9ded-864f2ec78426

**Comment by yonahd** [comment]
Done
