### ISSUE TITLE
feat: add autocompletion and manpage

### ISSUE THREAD

**Issue by chenrui333** [yonahd/kor#32]
some refs:
- https://github.com/cli/cli/commit/d9ef40c873afda892b63b422cb7a359b44f88951
- https://github.com/cli/cli/issues/900

**Comment by yonahd** [comment]
@chenrui333 Is this something you want to take on?
Or should I add this to the backlog?

**Comment by yonahd** [comment]
Autocompletion exists in cobra out of the box.
Man page can be added

**Comment by yonahd** [comment]
https://github.com/golang/go/issues/101
