### ISSUE TITLE
Discuss: Add Delete Option for Unused Resources

### ISSUE THREAD

**Issue by loaynaser3** [yonahd/kor#38]
I'm a new user of Kor, and I'm already impressed with how great of a tool it is! With that said, 
I'd like to propose an enhancement or new feature for consideration.

**Enhancement Proposal**

addition of a `--delete` option for unused resources in the kor tool. 
This enhancement would provide users with the ability to delete resources that are identified as unused.

**Expected behavior**

The deletion process should be initiated for the unused resources.
The command should provide feedback on the deletion process, indicating which resources are being deleted and their status.

**Comment by yonahd** [comment]
Hi @loaynaser3 
While this would be a great feature, I don't want to put this in the tool.
The main reason is that the tool does not 100% guarantee the resource is unused as you can see here https://github.com/yonahd/kor#supported-resources-and-limitations
And with CRD's we can detect if they are using a resource as well.

If someone wants to use this to delete despite this warning they can import kor and easily get the resources to delete

**Comment by yonahd** [comment]
Reopening.
We might implement this with a safe delete

**Comment by ozgurcd** [comment]
I believe a --dry-run option would be a nice addition at the same time.

**Comment by yonahd** [comment]
> I believe a --dry-run option would be a nice addition at the same time.

Hi @ozgurcd
What do you mean dry run?
Isn't the regular output of the tool a dry run?

Regardless when we put in the delete feature it will be implemented in a safe interactive way

**Comment by ozgurcd** [comment]
Yeah, you're right.
