### ISSUE TITLE
Excluding labels doesn't work

### ISSUE THREAD

**Issue by nemcikjan** [yonahd/kor#384]
**Describe the bug**
If using cli with `-l/--exclude-labels` flag, the filtering is not working

**To Reproduce**
Resource labels:
```
kubectl get pvc -n default pvc-claim-2 -o jsonpath={.metadata.labels}

{"kor/report":"false","reporting":"no"}
```
Command:
```
kor -l reporting=no persistentvolumeclaim
```
Output:
```
kor version: vdev

  _  _____  ____
 | |/ / _ \|  _ \
 | ' / | | | |_) |
 | . \ |_| |  _ <
 |_|\_\___/|_| \_\

Unused resources in namespace: "default"
+---+---------------+---------------+
| # | RESOURCE TYPE | RESOURCE NAME |
+---+---------------+---------------+
| 1 | Pvc           | pvc-claim-2   |
+---+---------------+---------------+
```

**Expected behavior**
The resources shouldn't be matched but the output is the following:
```
kor --exclude-labels reporting=no persistentvolumeclaim
kor version: vdev

  _  _____  ____
 | |/ / _ \|  _ \
 | ' / | | | |_) |
 | . \ |_| |  _ <
 |_|\_\___/|_| \_\

Unused resources in namespace: "default"
+---+---------------+---------------+
| # | RESOURCE TYPE | RESOURCE NAME |
+---+---------------+---------------+
| 1 | Pvc           | pvc-claim-2   |
+---+---------------+---------------+
```

**OS version, architecture and kor version**
Darwin_arm64
Kor version: vdev (brew installation of stable version 0.5.6)

**Comment by yonahd** [comment]
Marking this as a bug
@nemcikjan in the meantime can you try this https://github.com/yonahd/kor?tab=readme-ov-file#ignore-resources
This should help exclude the resource

**Comment by doronkg** [comment]
/assign
Not all resources were refactored with the new filtering interface, I'll create a PR for that.
