### ISSUE TITLE
Wrongly marks a configmap as unused

### ISSUE THREAD

**Issue by almilaneze** [yonahd/kor#385]
**Describe the bug**
When a configmap is used to provide environment variables to a initContainer (envFrom) this is not evaluated. As a result such a cm is marked as not used and if it is removed then on a new pod creation (for whatever reasons) it will fail as the corresponding configmap for providing environment vars to the  initContainer will be missing. 

**To Reproduce**

- have a pod with initContainer that gets env vars from a configmap
- check for unused configmaps in the namespace where the above pod is running

**Expected behavior**
Additional validation for initContainer's 'envFrom' section will be needed to check if it contains 'ConfigMapRef' section.

**Screenshots**

**OS version, architecture and kor version**
x86_64 GNU/Linux
Kor version: 0.1.14

**Additional context**

**Comment by yonahd** [comment]
> Hi Yonah, I can take care of fixing this one.

Go for it.
Please make this fix also for the secrets and add a test for this case
