### ISSUE TITLE
feature request: Export Prometheus metrics

### ISSUE THREAD

**Issue by Razgoldenberg1** [yonahd/kor#40]
**Summary**
I would like to suggest that the Kor project be updated to support Prometheus metrics.
CLI is very useful but allows users to collect and monitor Kor's metrics using Prometheus giving consistent visibility to the Kubernetes Orphaned Resources on your cluster.

**Comment by yonahd** [comment]
Hi @Razgoldenberg1 
What kind of metrics do you propose to export?

**Comment by Razgoldenberg1** [comment]
Hi @yonahd thanks for the quick response,
To start I would like to get the same output as on the CLI .
if we could get the name of the resource, namespace, and kind it would be very nice:
something like that:
Kubernetes_Orphaned_Resources{kind="configmap", namespace="default" ,name="my_configmap", age="265days"}

**Comment by yonahd** [comment]
Interesting proposal.
Will look into this.

**Comment by loaynaser3** [comment]
@yonahd  have a look at this [commit](https://github.com/yonahd/kor/commit/611e4add7b63373a9bf47cdece8841a251c3f118 )
may be helpful for this issue |output example:
```
Kubernetes_Orphaned_Resources{kind="Service",namespace="okteto",resourceName="rafiki"} 0
Kubernetes_Orphaned_Resources{kind="Secret",namespace="prometheus",resourceName="grafana-tls-certificate"} 0
```
regarding adding the age of the resource still not available

**Comment by yonahd** [comment]
Thanks!
This feature doesn't make so much sense as this is just a cli tool at this point.
This feature will be useful down the road when we support running this as a server. But for now this is in the backlog.

**Comment by yonahd** [comment]
@loaynaser3 this is now more relevant.
Would you like it assigned to you?

**Comment by Yuni-sa** [comment]
I can also help with this if needed, would be better to start working on it after #78 is merged.

**Comment by yonahd** [comment]
Thanks @Yuni-sa!
I'll create a release(with a docker image) and then we can move forward with the Helm chart.

Regarding the metrics I don't see a reason to complicate with the push gateway. We can have the deployment offer metrics or/and slack messages, While the cron will only offer slack.

**Comment by loaynaser3** [comment]
> @loaynaser3 this is now more relevant. Would you like it assigned to you?

yea sure, you can assign it

**Comment by yonahd** [comment]
> > @loaynaser3 this is now more relevant. Would you like it assigned to you?
> 
> yea sure, you can assign it

Assigned. I beleive @Yuni-sa can assist or take it if you need
