### ISSUE TITLE
Feature request: Support deletions of output

### ISSUE THREAD

**Issue by doryer** [yonahd/kor#42]
As the CLI is supporting outputing unused resources which will lead probably to deletions for the cluster, i would like to have `--delete` flag which executes deletions on the output of the command, Example:

kor secrets -n default --delete

secret foo deleted

Also important to support deletions from all namespaces, will be useful for Cronjobs across the cluster

**Comment by yonahd** [comment]
Duplicate of https://github.com/yonahd/kor/issues/38
