### ISSUE TITLE
Support yaml format output 

### ISSUE THREAD

**Issue by yonahd** [yonahd/kor#44]
In the output options support outputting in yaml format 
Using https://github.com/kubernetes-sigs/yaml/blob/v1.3.0/yaml.go#L82 we can support yaml and json using the same function.

**Comment by loaynaser3** [comment]
taking the current code and that you already can provide json response, here's a way that works and may fit your request
for example for configmap 
cmd/kor/configmaps.go

`if outputFormat == "json" {
	res, _ := kor.GetUnusedConfigmapsJSON(namespace, kubeconfig)
	fmt.Println(res)
} else if outputFormat == "yaml" {
	res, _ := kor.GetUnusedConfigmapsYAML(namespace, kubeconfig)
	fmt.Println(res)

} else {
	kor.GetUnusedConfigmaps(namespace, kubeconfig)
}`

pkg/kor/configmaps.go

`
import (

"sigs.k8s.io/yaml"

)



func GetUnusedConfigmapsYAML(namespace string, kubeconfig string) (string, error) {
	jsonResponse, err := GetUnusedConfigmapsJSON(namespace, kubeconfig)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Failed to process namespace %s: %v\n", namespace, err)
	}

	yamlResponse, err := yaml.JSONToYAML([]byte(jsonResponse))
	if err != nil {
		fmt.Printf("err: %v\n", err)
	}
	return (string(yamlResponse)), nil
}
`

**Comment by yonahd** [comment]
@loaynaser3 Yep. That is the idea.
Are you open to contributing this?

**Comment by loaynaser3** [comment]
Gladly 😊

**Comment by yonahd** [comment]
Great!
Assigned to you

**Comment by yonahd** [comment]
@loaynaser3 I see you closed the MR. Are you just reworking it or should I assign to someone else?

**Comment by loaynaser3** [comment]
@yonahd reworking 
i'll create a PR either tonight or tomorrow max ... 
BTW if issue #45 still unassigned you can assigne it to me also and i'll create a seperate PR for it

**Comment by yonahd** [comment]
Looks like someone started on it. https://github.com/yonahd/kor/pull/49
You can check with them if they intend to complete the work

**Comment by loaynaser3** [comment]
@yonahd  this issue can be closed, relted PR https://github.com/yonahd/kor/pull/56
