### ISSUE TITLE
Create option to label a resource for kor to mark as used

### ISSUE THREAD

**Issue by yonahd** [yonahd/kor#61]
Label should be 
```
kor/used=true
```
When the label is set to true kor should consider the resource as used.

**Comment by ozgurcd** [comment]
Can you elaborate ?  

To be sure, should kor ignore the resources labeled as "kor/used=true" even though they are not being used?

**Comment by yonahd** [comment]
> Can you elaborate ?
> 
> To be sure, should kor ignore the resources labeled as "kor/used=true" even though they are not being used?

Exactly. This way a user can protect his resources from being marked as unused.

This is a prerequisite for offering the delete option.

**Comment by ozgurcd** [comment]
Makes sense.

I am checking the code to see what we can do.

**Comment by ozgurcd** [comment]
https://github.com/yonahd/kor/pull/62
