### ISSUE TITLE
Support finding unused Cluster Roles

### ISSUE THREAD

**Issue by yonahd** [yonahd/kor#66]

**Comment by hzliangbin** [comment]
@yonahd

**Comment by yonahd** [comment]
Thanks!

**Comment by yonahd** [comment]
@hzliangbin Do you plan on working on this?
I would like this in the v0.3.0 release

**Comment by Azhovan** [comment]
@yonahd @hzliangbin 
let me know if I can work on this?

**Comment by yonahd** [comment]
> @yonahd @hzliangbin let me know if I can work on this?

If you don't get a response by Monday from @hzliangbin go for it.

**Comment by yonahd** [comment]
@Azhovan I assigned it to you

**Comment by Azhovan** [comment]
Thanks, I'll take care of that

**Comment by Azhovan** [comment]
@yonahd sorry i have been quite busy this week, I think i have time next week to submit a PR.

**Comment by omrico** [comment]
✋ assign

**Comment by hagay3** [comment]
wrong user 
please 
/assign
thanks :)

**Comment by hagay3** [comment]
WIP #198
