### ISSUE TITLE
Create a grafana dashboard to view kor metrics

### ISSUE THREAD

**Issue by yonahd** [yonahd/kor#97]

**Comment by Yuni-sa** [comment]
hi @yonahd can I be assigned/help with this issue?

**Comment by yonahd** [comment]
@Yuni-sa Sure.
Take a look at #118

**Comment by yonahd** [comment]
@Yuni-sa If you have feedback or want to share your ideas LMK.
Otherwise, I will merge sometime this week(changes can also be made afterwards)

**Comment by Yuni-sa** [comment]
@yonahd  take a look at #121
